# Clear the environment
rm(list = ls())

library(Seurat)
library(here)
library(reticulate)

# --- 1. Python/Conda Setup ---
env_python <- "/home/acflint/.conda/envs/spatrack_env/bin/python"
Sys.unsetenv("PYTHONPATH")
Sys.unsetenv("PYTHONHOME")
Sys.setenv(RETICULATE_PYTHON = env_python)

ad <- import("anndata")
message("Python environment loaded for AnnData export.")

# --- 2. Load the Clean Integrated Object ---
merged_path <- here("outputs", "Xenium_AldingerABT_combVZ&RLsubcluster_Res1.5_Merged_RDS", "XenAld_VZ_RL_QC_Subclusters_Spatial_Merged_Integrated2_4-23-26.rds")
message("Loading full integrated object...")
obj <- readRDS(merged_path)

# --- 3. Subset VZ Lineages ---
target_clusters <- c(
  "VZPs", "Maturing PCs", "Early-born PCs", "Late-born PCs", "Patterning PCs",
  "GABA Progenitors", "Golgi Cells", "MLIs", "iCN", 
  "RG Progenitors", "BG", "Astrocytes/Ependyma", "Ependymal Cells", 
  "OPCs", "Cycling Cells"
)

message("Subsetting to VZ lineages...")
vz_obj <- subset(obj, comb_subcluster %in% target_clusters)

# Clean up factor levels
vz_obj$comb_subcluster <- factor(vz_obj$comb_subcluster)
vz_obj$comb_subcluster <- droplevels(vz_obj$comb_subcluster)

# Free up massive RAM immediately
rm(obj)
gc()

# --- 4. Process: Generate VZ-Specific UMAP ---
message("Calculating zoomed-in UMAP for VZ lineages on the FULL dataset...")
# FIX: Use the .full reduction generated by ProjectIntegration
vz_obj <- RunUMAP(vz_obj, reduction = "integrated.harmony.full", dims = 1:30, reduction.name = "umap.vz")

# --- 5. Extract Biology and Topology ---
message("Extracting RNA, Metadata, and Dimensional Reductions...")
# Using the normalized data layer
expr_mat <- t(as.matrix(LayerData(vz_obj, assay = "Xenium", layer = "data")))
meta_data <- vz_obj@meta.data

# FIX: Extract the .full embeddings
harmony_coords <- Embeddings(vz_obj, reduction = "integrated.harmony.full")
umap_coords <- Embeddings(vz_obj, reduction = "umap.vz")

# --- 6. Extract Physics: Rebuild Spatial Coordinates from Raw Files ---
message("Bypassing Seurat spatial bugs: Extracting raw physical coordinates...")
all_samples <- unique(meta_data$sample_id)
spatial_list <- list()

for (samp in all_samples) {
  message(" -> Harvesting coordinates for: ", samp)
  raw_path <- here("outputs", "Xenium_AldingerABT_combVZ&RLsubcluster_Res1.5_RDS", paste0(samp, "_Ald_VZ_RL_QC_Subclusters.rds"))
  
  if (!file.exists(raw_path)) {
    stop("Raw file missing for sample: ", samp)
  }
  
  raw_obj <- readRDS(raw_path)
  coords <- GetTissueCoordinates(raw_obj, which = "centroids")
  
  rownames(coords) <- paste0(samp, "_", gsub(".*_", "", coords$cell))
  spatial_list[[samp]] <- coords[, c("x", "y")]
  
  rm(raw_obj)
  gc()
}

# Bind all sample coordinates together
all_spatial_coords <- do.call(rbind, spatial_list)
spatial_coords_matched <- as.matrix(all_spatial_coords[rownames(meta_data), ])

# --- 7. Bridge to Python and Save ---
message("Constructing AnnData object for CellRank 2.0...")
adata <- ad$AnnData(
  X = expr_mat,
  obs = meta_data,
  obsm = dict(
    X_harmony = harmony_coords,
    X_umap = umap_coords,
    spatial = spatial_coords_matched
  )
)

export_dir <- here("outputs", "Xenium_AldingerABT_combVZ&RLsubcluster_VZ_CellRank")
if (!dir.exists(export_dir)) dir.create(export_dir, recursive = TRUE)

export_path <- file.path(export_dir, "XenAld_VZ_RL_QC_Subclusters_Spatial_VZ_Integrated_4-29-26.h5ad")
adata$write(export_path)

message("Export complete! VZ data successfully packaged for CellRank 2.0 at: ", export_path)